### ISSUE TITLE
Model extraction in batch mode

### ISSUE THREAD

**Issue by aremazeilles** [ipa320/ros-model-cloud#35]
I am willing to extract automatically the model of a node, but in batch. I am searching whether I could, from the model you extract, generate automatically some ros test scripts.  

On one side, I would like to get that extraction in batch mode. To do so I basically need to comment the lines creating the web server from file [ws_setup.sh](https://github.com/ipa320/ros-model-cloud/blob/master/docker_local_configuration/ros_kinetic/ws_setup.sh#L12). Do you think we could adjust the docker creation to have two levels: one creating the image with the haros and model extraction tooling, and another adding to it the web server functionality? Or having a flag to launch the docker image without the extraction functionality?

Then, I would like to parse the model extracted. This is unclear to me what is the format of the result file `my_node.ros`. Following your example parsing `mimic` from `con_mimic`, I get:

```
PackageSet { package { 
  CatkinPackage cob_mimic { artifact {
    Artifact mimic {
      node Node { name mimic
        serviceserver {
          ServiceServer { name 'set_mimic' service 'cob_mimic.SetMimic'}}
        actionserver {
          ActionServer { name '?' action 'cob_mimic.SetMimicAction'}}
}}}}}}
```
This is not clear what is this file structure. Do you know if I could easily read such file in python?

**Comment by ipa-nhg** [comment]
Great idea! :tada: 

I think I should first introduce my work:

The .ros format correspond to a DSL that I create to describe ros nodes. The main contribution of my full work is a [Toolchain](https://github.com/ipa320/ros-model/#ros-tooling-manual) (eclipse based) that allows the definition of ROS nodes and systems using models, for these models I created Ecore metamodels plus the full Xtext+Xtend machinery, thanks to this I created a new DSL to formalize the definition of ROS software. 
This DSL incorporates graphical editor, textual editor with grammar checkers, rules validators at design time (for example if you connect a pub and sub with the same msg type, or also just if you follow the ROS naming conventions) and finally it incorporates code generators. To lower the entry barrier for ROS developers I integrated HAROS to automatically extract from the original source code the .ros model that follows my DSL language ( this is the functionality you see here ), additionally I have also a script that allow introspection at runtime and for a running system extract also automatically my model.
Apart of the .ros model I have also the .rossystem model which describes a ros system (mainly the information of a launch file). In case you also have interest on launch file tests.


If I understood correctly, you want to take the information of the extraction and generate new code based on that information. 
1. My tooling contains .ros interprets that can automatically generate code but then your code has to be integrated using Xtend language on my toolchain, this is the most quality-assurance method to generate code but probably it is completely out of your architecture idea. 
2. We have already a [python parser](https://github.com/ipa-hsd/rosgraph_monitor/blob/master/src/rosgraph_monitor/parser.py) for one of my models (the .rossytem one) extend this to the .ros model should be quite simple (it makes also sense for me to do that) and then you can use it to inject the information to the code generator. 
3. The third option will be use directly the [ros_model_extractor](https://github.com/ipa320/ros-model-cloud/blob/master/extractor-interface/scripts/ros_model_extractor.py) of this repository, you can take a look at the code and check how easy could be for you to integrate it.

In case your software will also be open source, it would be great if you go for the option 2. Then we can make both efforts compatible, and on my own experience if you want to generate code it is easier if you have a formal model that support the generator behind of it.

About add some custom tags for [these docker containers](https://github.com/ipa320/ros-model-cloud/tree/master/docker_local_configuration), I am completely open to modify the files.

**Comment by aremazeilles** [comment]
Thanks for that detailed explanation!
Solution 2 would make sense to me. Using  your python parser would not be a problem in my opinion. And yes, the objective would be to set it open source.

In the package generator, I recently added a [template](https://github.com/tecnalia-advancedmanufacturing-robotics/ros_pkg_gen/tree/master/package_generator_templates/templates/nodetest) for generating tests based on rostest. I will also soon publish another tool for testing services, and filter-like nodes. From the model you extract, I could then suggest and generate appropriate node tests. That is the idea...

Now, I am not familiar at all with DSL, as you have seen in my code. 
I just tried the python parser you mention, but I get an error

```shell
  File "parser.py", line 212, in <module>
    print(parser.parse().dump())
  File "parser.py", line 192, in parse
    self._result = ParseResults()
TypeError: __new__() takes at least 2 arguments (1 given)
```
Do you want me to bring this to that other repository?
Thanks for your time!

**Comment by aremazeilles** [comment]
I got the reason why: the parser is to be used with python3, and not python 2. Sorry for that

Given all this, I think we can close that issue, right? I may suggest some docker adjustment, and then should we open an issue in rosgraph_monitor to look at the .ros DSL parsing ?

**Comment by ipa-nhg** [comment]
Feel free to modify the Docker containers and send a PR to this Repo. 
The current python parser covers only the .rossystem model it has to be extended to support also the .ros one. I talked with @ipa-hsd, who is the maintainer of rosgrap_monitor and agreed to create a new ROS package to hold both parsers together, I think it is the cleanest solution. I will work today on the first draft of this new package, and move this issue there.

**Comment by aremazeilles** [comment]
Perfect, thanks

**Comment by ipa-nhg** [comment]
superseded  by https://github.com/ipa320/ros_model_parser/issues/1
