### ISSUE TITLE
Integrate the launch files analysis

### ISSUE THREAD

**Issue by ipa-nhg** [ipa320/ros-model-cloud#4]
Version of the script: https://github.com/ipa-nhg/ros-model/blob/HarosForLaunchExtractor/tools/ros_model_extractor.py

This has to be called with the arguments:
`ros_model_extractor.py --package *package_name* --name *launch_file* --launch`

Process:

- clone the repository that contains the launch file
- analyses the launch file or package.xml of the package to get all the required dependencies of the package
- clone all the source code repositories of all the required dependencies 
  - to locate the github URI the `roslocate` command can be used
  - we can generate a `rosinstall` file that contains all the dependencies and its src code address 
- run `roslaunch_dump` to resolve arguments
- build
- call the script to extract the `.ros` files and the `.rosystem` file

Some warnings should be showed:
- if for one of the required packages (depends) the src code can not be found in rosdistro (roslocate) -> verify that this not kill the script?? @ipa-nhg

**Comment by erogleva** [comment]
Integrated in #17
